[project]
name = "gc-bridge-4"
version = "0.1.0"
description = "GC-Bridge-4"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.2",
    "django-unfold",
    "psycopg[binary]",
    "lib-shopware6-api-base",
    "loguru",
    "pywin32; platform_system == 'Windows'",
]
